/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgTrain;

import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class MainUI extends javax.swing.JFrame {

    private MainUI MainUI;

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        pnlChangeCost.setVisible(false);
        pnlTotalCost.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpClass = new javax.swing.ButtonGroup();
        btngrpReturn = new javax.swing.ButtonGroup();
        TabbedPane = new javax.swing.JTabbedPane();
        pnlCheckPrice = new javax.swing.JPanel();
        lblFrom = new javax.swing.JLabel();
        cmbFrom = new javax.swing.JComboBox<>();
        lblTo = new javax.swing.JLabel();
        cmbTo = new javax.swing.JComboBox<>();
        lblNumber = new javax.swing.JLabel();
        txtNoOfPassengers = new javax.swing.JTextField();
        lblClass = new javax.swing.JLabel();
        rbtnFirst = new javax.swing.JRadioButton();
        rbtnSecond = new javax.swing.JRadioButton();
        lblReturn = new javax.swing.JLabel();
        btnCost = new javax.swing.JButton();
        rbtnYes = new javax.swing.JRadioButton();
        rbtnNo = new javax.swing.JRadioButton();
        pnlTotalCost = new javax.swing.JPanel();
        lblCostperPerson = new javax.swing.JLabel();
        txtCostperTicket = new javax.swing.JTextField();
        lblTotalCost = new javax.swing.JLabel();
        txtTotalCost = new javax.swing.JTextField();
        btnOk = new javax.swing.JToggleButton();
        pnlAdminLogin = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        pnlChangeCost = new javax.swing.JPanel();
        lblCostFirst = new javax.swing.JLabel();
        lblCostSecond = new javax.swing.JLabel();
        txtCostSecond = new javax.swing.JTextField();
        btnDone = new javax.swing.JButton();
        txtCostFirst = new javax.swing.JTextField();
        pnlTimeTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblTimeTable = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblWelcome1 = new javax.swing.JLabel();
        lblWelcome2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHelp = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Local Train (Pune<->Lonavala)");
        setResizable(false);

        pnlCheckPrice.setBackground(new java.awt.Color(0, 153, 153));

        lblFrom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFrom.setText("From:");

        cmbFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECT>", "Pune Junction", "Shivajinagar", "Khadki", "Dapodi", "Kasarwadi", "Pimpri", "Chinchwad", "Akurdi", "Dehu Road", "Begdewadi", "Ghorawadi", "Talegaon", "Vadgaon", "Kanhe", "Kamshet", "Malavli", "Lonavala" }));

        lblTo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTo.setText("To:");

        cmbTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECT>", "Pune Junction", "Shivajinagar", "Khadki", "Dapodi", "Kasarwadi", "Pimpri", "Chinchwad", "Akurdi", "Dehu Road", "Begdewadi", "Ghorawadi", "Talegaon", "Vadgaon", "Kanhe", "Kamshet", "Malavli", "Lonavala" }));

        lblNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumber.setText("No. Of Passengers:");

        lblClass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClass.setText("Class:");

        btngrpClass.add(rbtnFirst);
        rbtnFirst.setText("First");

        btngrpClass.add(rbtnSecond);
        rbtnSecond.setText("Second");

        lblReturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReturn.setText("Return:");

        btnCost.setText("Cost");
        btnCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCostActionPerformed(evt);
            }
        });

        btngrpReturn.add(rbtnYes);
        rbtnYes.setText("Yes");

        btngrpReturn.add(rbtnNo);
        rbtnNo.setText("No");

        pnlTotalCost.setBackground(new java.awt.Color(255, 204, 51));

        lblCostperPerson.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblCostperPerson.setText("Cost per person:");

        lblTotalCost.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblTotalCost.setText("Total Cost:");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTotalCostLayout = new javax.swing.GroupLayout(pnlTotalCost);
        pnlTotalCost.setLayout(pnlTotalCostLayout);
        pnlTotalCostLayout.setHorizontalGroup(
            pnlTotalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalCostLayout.createSequentialGroup()
                .addGroup(pnlTotalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTotalCostLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlTotalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlTotalCostLayout.createSequentialGroup()
                                .addComponent(lblTotalCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalCost))
                            .addComponent(lblCostperPerson))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCostperTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTotalCostLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnOk)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlTotalCostLayout.setVerticalGroup(
            pnlTotalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalCostLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlTotalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostperPerson)
                    .addComponent(txtCostperTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTotalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCost)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCheckPriceLayout = new javax.swing.GroupLayout(pnlCheckPrice);
        pnlCheckPrice.setLayout(pnlCheckPriceLayout);
        pnlCheckPriceLayout.setHorizontalGroup(
            pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCheckPriceLayout.createSequentialGroup()
                        .addComponent(lblFrom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTo))
                    .addGroup(pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCheckPriceLayout.createSequentialGroup()
                            .addComponent(lblNumber)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNoOfPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCheckPriceLayout.createSequentialGroup()
                            .addGroup(pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblReturn)
                                .addComponent(lblClass))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCheckPriceLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(rbtnFirst)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbtnSecond))
                                .addGroup(pnlCheckPriceLayout.createSequentialGroup()
                                    .addGroup(pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCost)
                                        .addGroup(pnlCheckPriceLayout.createSequentialGroup()
                                            .addComponent(rbtnYes)
                                            .addGap(18, 18, 18)
                                            .addComponent(rbtnNo)))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(44, 44, 44)
                .addGroup(pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnlCheckPriceLayout.setVerticalGroup(
            pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom)
                    .addComponent(cmbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo)
                    .addComponent(cmbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCheckPriceLayout.createSequentialGroup()
                        .addGroup(pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumber)
                            .addComponent(txtNoOfPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClass)
                            .addComponent(rbtnFirst)
                            .addComponent(rbtnSecond))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCheckPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblReturn)
                            .addComponent(rbtnYes)
                            .addComponent(rbtnNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCost))
                    .addComponent(pnlTotalCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        TabbedPane.addTab("Check Price", pnlCheckPrice);

        pnlAdminLogin.setBackground(new java.awt.Color(153, 51, 0));

        pnlLogin.setBackground(new java.awt.Color(102, 102, 102));

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 0));
        lblUsername.setText("Username:");
        lblUsername.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Password:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnLogin)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlChangeCost.setBackground(new java.awt.Color(255, 255, 51));

        lblCostFirst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCostFirst.setText("Cost per station(First Class):");

        lblCostSecond.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCostSecond.setText("Cost per Station(Second Class):");

        txtCostSecond.setText("5");

        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        txtCostFirst.setText("20");

        javax.swing.GroupLayout pnlChangeCostLayout = new javax.swing.GroupLayout(pnlChangeCost);
        pnlChangeCost.setLayout(pnlChangeCostLayout);
        pnlChangeCostLayout.setHorizontalGroup(
            pnlChangeCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChangeCostLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlChangeCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChangeCostLayout.createSequentialGroup()
                        .addComponent(lblCostSecond)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCostSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDone)
                        .addGap(41, 41, 41))
                    .addGroup(pnlChangeCostLayout.createSequentialGroup()
                        .addComponent(lblCostFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCostFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlChangeCostLayout.setVerticalGroup(
            pnlChangeCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChangeCostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChangeCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostFirst)
                    .addComponent(txtCostFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlChangeCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostSecond)
                    .addComponent(txtCostSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChangeCostLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDone)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlAdminLoginLayout = new javax.swing.GroupLayout(pnlAdminLogin);
        pnlAdminLogin.setLayout(pnlAdminLoginLayout);
        pnlAdminLoginLayout.setHorizontalGroup(
            pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(pnlChangeCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pnlAdminLoginLayout.setVerticalGroup(
            pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlChangeCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Admin Login", pnlAdminLogin);

        lblTimeTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgTrain/Images/timetable.jpg"))); // NOI18N
        lblTimeTable.setText("TimeTable");
        jScrollPane2.setViewportView(lblTimeTable);

        javax.swing.GroupLayout pnlTimeTableLayout = new javax.swing.GroupLayout(pnlTimeTable);
        pnlTimeTable.setLayout(pnlTimeTableLayout);
        pnlTimeTableLayout.setHorizontalGroup(
            pnlTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );
        pnlTimeTableLayout.setVerticalGroup(
            pnlTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Time-Table", pnlTimeTable);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgTrain/Images/train.png"))); // NOI18N
        lblImage.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(200, 0, 50)));

        lblWelcome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgTrain/Images/welcome.png"))); // NOI18N
        lblWelcome1.setText("jLabel2");
        lblWelcome1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(200, 0, 50)));

        lblWelcome2.setFont(new java.awt.Font("Gungsuh", 1, 18)); // NOI18N
        lblWelcome2.setForeground(new java.awt.Color(51, 51, 255));
        lblWelcome2.setText("WELCOME");
        lblWelcome2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(240, 240, 240));

        mnuHelp.setBackground(new java.awt.Color(255, 204, 0));
        mnuHelp.setBorder(null);
        mnuHelp.setText("Help");

        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuAbout);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWelcome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_mnuAboutActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       if(txtUsername.getText().equals("Naveen"))
       {
           if(pfPassword.getText().equals("Naveen"))
           {
              pnlChangeCost.setVisible(true);
               return;
           }
           else
           {
               JOptionPane.showMessageDialog(MainUI.this,"Invalid Password");
               pfPassword.grabFocus();
           }  
       }
       else
       {
           JOptionPane.showMessageDialog(MainUI.this,"Invalid username");
           txtUsername.grabFocus();
       }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
              if(txtCostFirst.getText().equals("")||txtCostSecond.getText().equals(""))
              {
                  JOptionPane.showMessageDialog(MainUI.this, "Cost fields cannot be empty");
                  return;
              }
              
        
              pnlChangeCost.setVisible(false);
              txtUsername.setText("");
              pfPassword.setText("");     
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCostActionPerformed
            if(validateInput()==false)
                return;
            
            int x=cmbFrom.getSelectedIndex();
            int y=cmbTo.getSelectedIndex();
            
            int z=Math.abs(y-x);
            int costPerTicket=0;
            int TotalCost;
            if(rbtnFirst.isSelected())
            {
                costPerTicket=z*Integer.parseInt(txtCostFirst.getText());
                TotalCost=costPerTicket*Integer.parseInt(txtNoOfPassengers.getText()); 
            }
            else
            {
                costPerTicket=z*Integer.parseInt(txtCostSecond.getText());
                TotalCost=costPerTicket*Integer.parseInt(txtNoOfPassengers.getText());
            }
            
            if(rbtnYes.isSelected())
            {
                TotalCost=2*TotalCost;
                costPerTicket=2*costPerTicket;
            }
            
            pnlTotalCost.setVisible(true);
            txtCostperTicket.setText(Integer.toString(costPerTicket));
            txtTotalCost.setText(Integer.toString(TotalCost));
                    
    }//GEN-LAST:event_btnCostActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
            cmbFrom.setSelectedIndex(0);
            cmbTo.setSelectedIndex(0);
            txtNoOfPassengers.setText("");
            btngrpClass.clearSelection();
            btngrpReturn.clearSelection();
            txtCostperTicket.setText("");
            txtTotalCost.setText("");
            pnlTotalCost.setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    
    public static void main(String args[]) {
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton btnCost;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnLogin;
    private javax.swing.JToggleButton btnOk;
    private javax.swing.ButtonGroup btngrpClass;
    private javax.swing.ButtonGroup btngrpReturn;
    private javax.swing.JComboBox<String> cmbFrom;
    private javax.swing.JComboBox<String> cmbTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblCostFirst;
    private javax.swing.JLabel lblCostSecond;
    private javax.swing.JLabel lblCostperPerson;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JLabel lblTimeTable;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JLabel lblWelcome2;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPanel pnlAdminLogin;
    private javax.swing.JPanel pnlChangeCost;
    private javax.swing.JPanel pnlCheckPrice;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlTimeTable;
    private javax.swing.JPanel pnlTotalCost;
    private javax.swing.JRadioButton rbtnFirst;
    private javax.swing.JRadioButton rbtnNo;
    private javax.swing.JRadioButton rbtnSecond;
    private javax.swing.JRadioButton rbtnYes;
    private javax.swing.JTextField txtCostFirst;
    private javax.swing.JTextField txtCostSecond;
    private javax.swing.JTextField txtCostperTicket;
    private javax.swing.JTextField txtNoOfPassengers;
    private javax.swing.JTextField txtTotalCost;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void JOptionPane(MainUI aThis, String invalid) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private boolean validateInput() {
        
        if(cmbFrom.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(MainUI.this, "Select Source Station");
            cmbFrom.grabFocus();
            return false;
        }
        
        if(cmbTo.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(MainUI.this, "Select Destination Station");
            cmbTo.grabFocus();
            return false;
        }
        
        if(txtNoOfPassengers.getText().equals(""))
        {
            JOptionPane.showMessageDialog(MainUI.this, "Enter Number of passengers");
            txtNoOfPassengers.grabFocus();
            return false;
        }
        
        if(btngrpClass.isSelected(null))
        {
            JOptionPane.showMessageDialog(MainUI.this, "Select Class(First/Second)");
            lblClass.grabFocus();
            return false;
        }
        
        if(btngrpReturn.isSelected(null))
        {
            JOptionPane.showMessageDialog(MainUI.this, "Select Return(Yes/No)");
            lblClass.grabFocus();
            return false;
        }
        
       return true;
    }
}
